version: "3.8"

services:
  client:
    image: "lucasdev2001/minimolde-client"
    ports:
      - "80:5173"

  backend:
    image: "lucasdev2001/minimolde-backend"
    ports:
      - "3000:3000"

  broker:
    image: "lucasdev2001/minimolde-broker"
    ports:
      - "1883:1883"
      - "8888:8888"
